/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author carlo
 */
public class txtCifrar extends javax.swing.JFrame {

    /**
     * Creates new form txtCifrar
     */
    private String Texto;
    public txtCifrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B4096 = new javax.swing.JButton();
        B512 = new javax.swing.JButton();
        B1024 = new javax.swing.JButton();
        B2048 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        B4096.setBackground(new java.awt.Color(102, 255, 102));
        B4096.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B4096.setForeground(new java.awt.Color(0, 0, 0));
        B4096.setText("4096");
        B4096.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4096ActionPerformed(evt);
            }
        });

        B512.setBackground(new java.awt.Color(102, 255, 102));
        B512.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B512.setForeground(new java.awt.Color(0, 0, 0));
        B512.setText("512");
        B512.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B512ActionPerformed(evt);
            }
        });

        B1024.setBackground(new java.awt.Color(102, 255, 102));
        B1024.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B1024.setForeground(new java.awt.Color(0, 0, 0));
        B1024.setText("1024");
        B1024.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1024ActionPerformed(evt);
            }
        });

        B2048.setBackground(new java.awt.Color(102, 255, 102));
        B2048.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        B2048.setForeground(new java.awt.Color(0, 0, 0));
        B2048.setText("2048");
        B2048.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2048ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("CLAVE PARA CIFRAR");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ingrese el texto a Cifrar:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("TEXTO A CIFRAR");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Manzano Solis Carlos Emilio 5IV6");

        txtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addGap(0, 47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(B512)
                        .addGap(52, 52, 52)
                        .addComponent(B1024)
                        .addGap(77, 77, 77)
                        .addComponent(B2048)
                        .addGap(75, 75, 75)
                        .addComponent(B4096, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(229, 229, 229))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B512)
                    .addComponent(B1024)
                    .addComponent(B2048)
                    .addComponent(B4096, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B4096ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4096ActionPerformed
        resultado result = new resultado();
        Texto=txtField.getText();
        result.setLLave(4096, Texto);
        result.setVisible(true);
        result.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_B4096ActionPerformed

    private void B512ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B512ActionPerformed
        resultado result = new resultado();
        Texto=txtField.getText();
        result.setLLave(512, Texto);
        result.setVisible(true);
        result.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_B512ActionPerformed

    private void B1024ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1024ActionPerformed
        resultado result = new resultado();
        Texto=txtField.getText();
        result.setLLave(1024, Texto);
        result.setVisible(true);
        result.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_B1024ActionPerformed

    private void B2048ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2048ActionPerformed
        resultado result = new resultado();
        Texto=txtField.getText();
        result.setLLave(2048, Texto);
        result.setVisible(true);
        result.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_B2048ActionPerformed

    private void txtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldActionPerformed

    }//GEN-LAST:event_txtFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(txtCifrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(txtCifrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(txtCifrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(txtCifrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new txtCifrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1024;
    private javax.swing.JButton B2048;
    private javax.swing.JButton B4096;
    private javax.swing.JButton B512;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtField;
    // End of variables declaration//GEN-END:variables
}
